#include "Ellipse.h"
#include <iostream>



void Ellipse::EffectuerSaisie(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4C begin
{
    double X, Y;
    if (NoPoint == 1)
    {
        std::cout << "Entrez la position X et Y du coin haut gauche du rectangle enveloppant l'Ellipse: " << std::endl;
    }
    else
    {
        std::cout << "Entrez la position X et Y du coin bas droite du rectangle enveloppant l'Ellipse: " << std::endl;
    }
    std::cin >> X >> Y;
    PairePoints[NoPoint - 1].SetXY(X, Y);
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ellipse::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4F begin
{
    std::cout << "Dessin d'une Ellipse:" << std::endl;
    std::cout << "Position du coin haut gauche du rectangle enveloppant l'Ellipse: ";
    PairePoints[0].AfficherPoint();
    std::cout << "Position du coin bas droite du rectangle enveloppant l'Ellipse: ";
    PairePoints[1].AfficherPoint();
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ellipse::Ellipse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B51 begin
{
    std::cout << "Constructeur d'Ellipse" << std::endl;
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B51 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ellipse::~Ellipse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B53 begin
{
    std::cout << "Destructeur d'Ellipse" << std::endl;
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
