#include "Figure.h"
#include <iostream>



void Figure::EffectuerSaisie(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D86 begin
{
   
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D86 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Figure::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D89 begin
{
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D89 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Figure::Figure()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8B begin
{
    PairePoints[0].SetXY(0, 0);
    PairePoints[1].SetXY(0, 0);

    std::cout << "Constructeur de Figure" << std::endl;
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Figure::~Figure()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8D begin
{
    std::cout << "Destructeur de Figure" << std::endl;
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
