#include "Rectangle.h"
#include <iostream>



void Rectangle::EffectuerSaisie(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B43 begin
{
    double X, Y;
    if (NoPoint == 1)
    {
        std::cout << "Entrez la position X et Y du coin haut gauche du rectangle: " << std::endl;
    }
    else
    {
        std::cout << "Entrez la position X et Y du coin bas droite du rectangle: " << std::endl;
    }
    std::cin >> X >> Y;
    PairePoints[NoPoint - 1].SetXY(X, Y);
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B43 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rectangle::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B46 begin
{
    std::cout << "Dessin d'un Rectangle:" << std::endl;
    std::cout << "Position du coin haut gauche du rectangle: ";
    PairePoints[0].AfficherPoint();
    std::cout << "Position du coin bas droite du rectangle: ";
    PairePoints[1].AfficherPoint();
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rectangle::Rectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B48 begin
{
    std::cout << "Constructeur de Rectangle" << std::endl;
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B48 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rectangle::~Rectangle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4A begin
{
    std::cout << "Destructeur de Rectangle" << std::endl;
}
// section -64--88-1-58--68192eb5:13c5971b46e:-8000:0000000000000B4A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
