#include "Cercle.h"
#include <cmath>
#include <iostream>
#include <iomanip>



double Cercle::CalculerSurface(double diametre, double nul)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 begin
{
    Surface = 3.14159265 * (pow(diametre, 2))/4;
    return Surface;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D74 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre, double nul)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A begin
{
    Perimetre = 3.14159265 * diametre;
    return Perimetre;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Cercle::Cercle()
{
    std::cout << "Constructeur de Cercle" << std::endl;
}