#include "Cercle.h"




double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F8F begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F8F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F92 begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F92 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
