#include "Ex1.h"




int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F57 begin
{
    return 0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F57 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F5C begin
{
    return 0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F5C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F5E begin
{
    
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F61 begin
{
    
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F64 begin
{
    
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
