#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F6E begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F6E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F72 begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F72 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F76 begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F76 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F78 begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F78 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
