#include "Rectangle.h"




double Rectangle::CalculerSurface(double largeur, double CalculerPerimetre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F85 begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F85 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F89 begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F89 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
