#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F7B begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F7B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double base, char hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F7F begin
{
    return 0.0;
}
// section 10--28--98-76-c404dfe:18bf0f7554d:-8000:0000000000000F7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
